site_name:
  Festo Applied Motion -- Python-based control for Festo electrically-driven
  motion components
site_url: https://symmetrical-barnacle-r232pev.pages.github.io
repo_url: https://github.com/Festo-se/festo-dev-applied-motion

site_dir: public
docs_dir: docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Light mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Dark mode

  logo: img/Festo_Logo_Caerul_Web.svg
  favicon: img/method.png
  features: navigation.sections content.code.copy content.tooltips

use_directory_urls: true

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: class
          class: highlight
          format: !!python/name:pymdownx.highlight.highlight
plugins:
  - codeinclude
  - search
  - include-markdown
  - live-edit
  - autorefs:
      resolve_closest: true
  - mkdocs-autoapi:
      autoapi_dir: src
      autoapi_add_nav_entry: true
      autoapi_generate_api_docs: true
      autoapi_file_patterns:
        - "*.py"

  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: google
            docstring_section_style: table
            members_order: source
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            heading_level: 2
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            merge_init_into_class: true
            inherited_members: true
            filters:
              - "!^_"
              - "^__init__$"

extra_css:
  - css/extra.css
  - https://www.festo.com/fonts/fonts.css

nav:
  - Home: "index.md"
  - Getting Started: "getting-started/index.md"
  - User Guide:
      - "FPosBAPI Backend": "user-guide/fposbapi.md"
      - "festo-edcon / Modbus Backend": "user-guide/edcon.md"
      - "CLI Reference": "user-guide/cli.md"
  - Examples:
      - "FPosBAPI": "examples/fposbapi.md"
      - "festo-edcon / Modbus": "examples/edcon.md"
  - Festo Resources:
      - "CMMT Product Page":
          "https://www.festo.com/us/en/p/servo-drive-for-synchronous\
          -motors-id_CMMT-ST/"
  - Issues Tracker:
      - "Report an Issue": "https://github.com/Festo-se/festo-dev-applied-motion/issues"
