[project]
name = "festo-dev-applied-motion"
version = "0.3.8"
authors = [
    { name = "Kyle Wardlow", email = "kyle.wardlow@festo.com" }
]
description = "Quality of life library for controlling Festo electrically-driven, motion components"
requires-python = ">=3.10"
dependencies = [
    "festo-edcon>=1.0.1",
]

[project.scripts]
applied-motion-teach = "applied_motion.cli.cli:main"

[project.urls]
Homepage = "https://github.com/Festo-se/festo-dev-applied-motion/"
Repository = "https://github.com/Festo-se/festo-dev-applied-motion.git"
Issues = "https://github.com/Festo-se/festo-dev-applied-motion/issues"

[project.optional-dependencies]
cli = [
    "prompt-toolkit>=3.0.52",
    "rich>=14.2.0",
]

[build-system]
requires = ["uv_build>=0.11,<0.13"]
build-backend = "uv_build"

[dependency-groups]
teach = [
    "prompt-toolkit>=3.0",
    "rich>=13.0",
]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "ruff>=0.15.11",
    "ty>=0.0.34",
    {include-group = "teach"}
]
docs = [
    "mkdocs>=1.6.1,<2",
    "mkdocs-autoapi>=0.4.1",
    "mkdocs-autorefs>=1.4.2",
    "mkdocs-include-markdown-plugin>=7.1.5",
    "mkdocs-material>=9.6.14",
    "mkdocstrings[python]>=0.29.1",
    "mkdocs-codeinclude-plugin>=0.2.1",  
]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "hardware: marks tests that require connected hardware (deselect with -m 'not hardware')",
]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s %(levelname)s %(name)s: %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_level = "WARNING"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { git = { commit = true } }]

[tool.uv.build-backend]
module-name = "applied_motion"

[tool.ty.src]
include = [
    "src"
]
exclude = [
    "tests"
]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py310"
src = ["src", "examples"]
exclude = [
    "**/.git",
    "**/__pycache__",
    "**/.vscode",
    "**/.venv",
    "**/.pytest_cache",
    "**/tests",
]
fix = true
show-fixes = true

[tool.ruff.lint]
select = ["D", "E4", "E7", "E9", "F", "C901", "B", "S"]
ignore = ["D203", "D212"]
exclude = ["tests/*",]

[tool.ruff.lint.per-file-ignores]
# Ignore D100 and D104 in all __init__.py files
"__init__.py" = ["D100", "D104"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
line-ending = "auto"
